server:
  port: 8888

spring:
  #项目名
  application:
    name: mszlu_blog
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/blog?
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis-plus 打印日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: ms_